name: Test JS

on:
  push:
    # Only run if JS-related files changed.
    paths:
      - '**.js'
      - '.nvmrc'
      - '**/package.json'
      - 'package-lock.json'
      - '.github/workflows/test-js.yml'
    branches:
      - main
  pull_request:
    # Only run if JS-related files changed.
    paths:
      - '**.js'
      - '.nvmrc'
      - '**/package.json'
      - 'package-lock.json'
      - '.github/workflows/test-js.yml'

jobs:
  test:
    name: Test JS
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Cache node modules
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        env:
          cache-name: cache-node-modules

      - name: Setup Jest cache
        uses: actions/cache@v2.1.4
        id: cache-jest-cache
        with:
          path: .jest-cache
          key: ${{ runner.os }}-${{ steps.nvm.outputs.NVMRC }}-jest

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run JavaScript unit tests
        run: npm run test:js -- --runInBand --ci --cacheDirectory="$HOME/.jest-cache"